//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTSharp.EntityFrameworkCore.MongoDB.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MongoDBStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MongoDBStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IoTSharp.EntityFrameworkCore.MongoDB.Properties.MongoDBStrings", typeof(MongoDBStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The time to live for analytical store was configured to &apos;{ttl1}&apos; on &apos;{entityType1}&apos;, but on &apos;{entityType2}&apos; it was configured to &apos;{ttl2}&apos;. All entity types mapped to the same container &apos;{container}&apos; must be configured with the same time to live for analytical store. 的本地化字符串。
        /// </summary>
        internal static string AnalyticalTTLMismatch {
            get {
                return ResourceManager.GetString("AnalyticalTTLMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MongoDB database does not support &apos;CanConnect&apos; or &apos;CanConnectAsync&apos;. 的本地化字符串。
        /// </summary>
        internal static string CanConnectNotSupported {
            get {
                return ResourceManager.GetString("CanConnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both the connection string and account key or account endpoint were specified. Specify only one set of connection details. 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringConflictingConfiguration {
            get {
                return ResourceManager.GetString("ConnectionStringConflictingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default time to live was configured to &apos;{ttl1}&apos; on &apos;{entityType1}&apos;, but on &apos;{entityType2}&apos; it was configured to &apos;{ttl2}&apos;. All entity types mapped to the same container &apos;{container}&apos; must be configured with the same default time to live. 的本地化字符串。
        /// </summary>
        internal static string DefaultTTLMismatch {
            get {
                return ResourceManager.GetString("DefaultTTLMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The discriminator value for &apos;{entityType1}&apos; is &apos;{discriminatorValue}&apos; which is the same for &apos;{entityType2}&apos;. Every concrete entity type mapped to the container &apos;{container}&apos; must have a unique discriminator value. 的本地化字符串。
        /// </summary>
        internal static string DuplicateDiscriminatorValue {
            get {
                return ResourceManager.GetString("DuplicateDiscriminatorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the etag property &apos;{property}&apos; on &apos;{entityType}&apos; is &apos;{propertyType}&apos;. All etag properties must be strings or have a string value converter. 的本地化字符串。
        /// </summary>
        internal static string ETagNonStringStoreType {
            get {
                return ResourceManager.GetString("ETagNonStringStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the &apos;{idProperty}&apos; property on &apos;{entityType}&apos; is &apos;{propertyType}&apos;. All &apos;id&apos; properties must be strings or have a string value converter. 的本地化字符串。
        /// </summary>
        internal static string IdNonStringStoreType {
            get {
                return ResourceManager.GetString("IdNonStringStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified entity type &apos;{derivedType}&apos; is not derived from &apos;{entityType}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidDerivedTypeInEntityProjection {
            get {
                return ResourceManager.GetString("InvalidDerivedTypeInEntityProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A FromSqlExpression has an invalid arguments expression type &apos;{expressionType}&apos; or value type &apos;{valueType}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidFromSqlArguments {
            get {
                return ResourceManager.GetString("InvalidFromSqlArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to generate a valid &apos;id&apos; value to execute a &apos;ReadItem&apos; query. This usually happens when the value provided for one of the properties is &apos;null&apos; or an empty string. Please supply a value that&apos;s not &apos;null&apos; or an empty string. 的本地化字符串。
        /// </summary>
        internal static string InvalidResourceId {
            get {
                return ResourceManager.GetString("InvalidResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both properties &apos;{property1}&apos; and &apos;{property2}&apos; on entity type &apos;{entityType}&apos; are mapped to &apos;{storeName}&apos;. Map one of the properties to a different JSON property. 的本地化字符串。
        /// </summary>
        internal static string JsonPropertyCollision {
            get {
                return ResourceManager.GetString("JsonPropertyCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed CreateItem ({elapsed} ms, {charge} RU) ActivityId=&apos;{activityId}&apos;, Container=&apos;{container}&apos;, Id=&apos;{id}&apos;, Partition=&apos;{partitionKey}&apos; 的本地化字符串。
        /// </summary>
        internal static string LogExecutedCreateItem {
            get {
                return ResourceManager.GetString("LogExecutedCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed DeleteItem ({elapsed} ms, {charge} RU) ActivityId=&apos;{activityId}&apos;, Container=&apos;{container}&apos;, Id=&apos;{id}&apos;, Partition=&apos;{partitionKey}&apos; 的本地化字符串。
        /// </summary>
        internal static string LogExecutedDeleteItem {
            get {
                return ResourceManager.GetString("LogExecutedDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed ReadItem ({elapsed} ms, {charge} RU) ActivityId=&apos;{activityId}&apos;, Container=&apos;{container}&apos;, Id=&apos;{id}&apos;, Partition=&apos;{partitionKey}&apos; 的本地化字符串。
        /// </summary>
        internal static string LogExecutedReadItem {
            get {
                return ResourceManager.GetString("LogExecutedReadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed ReadNext ({elapsed} ms, {charge} RU) ActivityId=&apos;{activityId}&apos;, Container=&apos;{container}&apos;, Partition=&apos;{partitionKey}&apos;, Parameters=[{parameters}]{newLine}{sql} 的本地化字符串。
        /// </summary>
        internal static string LogExecutedReadNext {
            get {
                return ResourceManager.GetString("LogExecutedReadNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executed ReplaceItem ({elapsed} ms, {charge} RU) ActivityId=&apos;{activityId}&apos;, Container=&apos;{container}&apos;, Id=&apos;{id}&apos;, Partition=&apos;{partitionKey}&apos; 的本地化字符串。
        /// </summary>
        internal static string LogExecutedReplaceItem {
            get {
                return ResourceManager.GetString("LogExecutedReplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading resource &apos;{resourceId}&apos; item from container &apos;{containerId}&apos; in partition &apos;{partitionKey}&apos;. 的本地化字符串。
        /// </summary>
        internal static string LogExecutingReadItem {
            get {
                return ResourceManager.GetString("LogExecutingReadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executing SQL query for container &apos;{containerId}&apos; in partition &apos;{partitionKey}&apos; [Parameters=[{parameters}]]{newLine}{commandText} 的本地化字符串。
        /// </summary>
        internal static string LogExecutingSqlQuery {
            get {
                return ResourceManager.GetString("LogExecutingSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;Reverse&apos; could not be translated to the server because there is no ordering on the server side. 的本地化字符串。
        /// </summary>
        internal static string MissingOrderingInSelectExpression {
            get {
                return ResourceManager.GetString("MissingOrderingInSelectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MongoDB-specific methods can only be used when the context is using the MongoDB provider. 的本地化字符串。
        /// </summary>
        internal static string MongoDBNotInUse {
            get {
                return ResourceManager.GetString("MongoDBNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation &apos;{entityType}.{navigationName}&apos; doesn&apos;t point to an embedded entity. 的本地化字符串。
        /// </summary>
        internal static string NavigationPropertyIsNotAnEmbeddedEntity {
            get {
                return ResourceManager.GetString("NavigationPropertyIsNotAnEmbeddedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; is sharing the container &apos;{container}&apos; with other types, but does not have a discriminator property configured. Configure a discriminator property and assign a unique value for this entity type. 的本地化字符串。
        /// </summary>
        internal static string NoDiscriminatorProperty {
            get {
                return ResourceManager.GetString("NoDiscriminatorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; is sharing the container &apos;{container}&apos; with other types, but does not have a discriminator value configured. Configure a unique discriminator value for this entity type. 的本地化字符串。
        /// </summary>
        internal static string NoDiscriminatorValue {
            get {
                return ResourceManager.GetString("NoDiscriminatorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; does not have a key declared on the &apos;{idProperty}&apos; property. Add a key to &apos;{entityType}&apos; that contains &apos;{idProperty}&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoIdKey {
            get {
                return ResourceManager.GetString("NoIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; does not have a property mapped to the &apos;id&apos; property in the database. Add a property mapped to &apos;id&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoIdProperty {
            get {
                return ResourceManager.GetString("NoIdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Including navigation &apos;{navigation}&apos; is not supported as the navigation is not embedded in same resource. 的本地化字符串。
        /// </summary>
        internal static string NonEmbeddedIncludeNotSupported {
            get {
                return ResourceManager.GetString("NonEmbeddedIncludeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; has property &apos;{property}&apos; configured as a concurrency token, but only a property mapped to &apos;_etag&apos; is supported as a concurrency token. Consider using &apos;PropertyBuilder.IsETagConcurrency&apos;. 的本地化字符串。
        /// </summary>
        internal static string NonETagConcurrencyToken {
            get {
                return ResourceManager.GetString("NonETagConcurrencyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; does not have a partition key set, but is mapped to the container &apos;{container}&apos; shared by entity types with partition keys. Configure a compatible partition key on &apos;{entityType}&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoPartitionKey {
            get {
                return ResourceManager.GetString("NoPartitionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity type &apos;{entityType}&apos; does not have a key declared on &apos;{partitionKey}&apos; and &apos;{idProperty}&apos; properties. Add a key to &apos;{entityType}&apos; that contains &apos;{partitionKey}&apos; and &apos;{idProperty}&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoPartitionKeyKey {
            get {
                return ResourceManager.GetString("NoPartitionKeyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no string-based representation of this query as it&apos;s executed using &apos;ReadItemQueryAsync({resourceId}, {partitionKey})&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoReadItemQueryString {
            get {
                return ResourceManager.GetString("NoReadItemQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression &apos;{sqlExpression}&apos; in the SQL tree does not have a type mapping assigned. 的本地化字符串。
        /// </summary>
        internal static string NullTypeMappingInSqlTree {
            get {
                return ResourceManager.GetString("NullTypeMappingInSqlTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MongoDB SQL does not allow Offset without Limit. Consider specifying a &apos;Take&apos; operation on the query. 的本地化字符串。
        /// </summary>
        internal static string OffsetRequiresLimit {
            get {
                return ResourceManager.GetString("OffsetRequiresLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity of type &apos;{entityType}&apos; is mapped as a part of the document mapped to &apos;{missingEntityType}&apos;, but there is no tracked entity of this type with the corresponding key value. Consider using &apos;DbContextOptionsBuilder.EnableSensitiveDataLogging&apos; to see the key values. 的本地化字符串。
        /// </summary>
        internal static string OrphanedNestedDocument {
            get {
                return ResourceManager.GetString("OrphanedNestedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity of type &apos;{entityType}&apos; is mapped as part of the document mapped to &apos;{missingEntityType}&apos;, but there is no tracked entity of this type with the key value &apos;{keyValue}&apos;. 的本地化字符串。
        /// </summary>
        internal static string OrphanedNestedDocumentSensitive {
            get {
                return ResourceManager.GetString("OrphanedNestedDocumentSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The partition key specified in the &apos;WithPartitionKey&apos; call &apos;{partitionKey1}&apos; and the partition key specified in the &apos;Where&apos; predicate &apos;{partitionKey2}&apos; must be identical to return any results. Remove one of them. 的本地化字符串。
        /// </summary>
        internal static string PartitionKeyMismatch {
            get {
                return ResourceManager.GetString("PartitionKeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to execute a &apos;ReadItem&apos; query since the partition key value is missing. Consider using the &apos;WithPartitionKey&apos; method on the query to specify partition key to use. 的本地化字符串。
        /// </summary>
        internal static string PartitionKeyMissing {
            get {
                return ResourceManager.GetString("PartitionKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The partition key for entity type &apos;{entityType}&apos; is set to &apos;{property}&apos;, but there is no property with that name. 的本地化字符串。
        /// </summary>
        internal static string PartitionKeyMissingProperty {
            get {
                return ResourceManager.GetString("PartitionKeyMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the partition key property &apos;{property}&apos; on &apos;{entityType}&apos; is &apos;{propertyType}&apos;. All partition key properties need to be strings or have a string value converter. 的本地化字符串。
        /// </summary>
        internal static string PartitionKeyNonStringStoreType {
            get {
                return ResourceManager.GetString("PartitionKeyNonStringStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The partition key property &apos;{property1}&apos; on &apos;{entityType1}&apos; is mapped as &apos;{storeName1}&apos;, but the partition key property &apos;{property2}&apos; on &apos;{entityType2}&apos; is mapped as &apos;{storeName2}&apos;. All partition key properties need to be mapped to the same store property for entity types mapped to the same container. 的本地化字符串。
        /// </summary>
        internal static string PartitionKeyStoreNameMismatch {
            get {
                return ResourceManager.GetString("PartitionKeyStoreNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to execute a &apos;ReadItem&apos; query since the &apos;id&apos; value is missing and cannot be generated. 的本地化字符串。
        /// </summary>
        internal static string ResourceIdMissing {
            get {
                return ResourceManager.GetString("ResourceIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reversing the ordering is not supported when limit or offset are already applied. 的本地化字符串。
        /// </summary>
        internal static string ReverseAfterSkipTakeNotSupported {
            get {
                return ResourceManager.GetString("ReverseAfterSkipTakeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provisioned throughput was configured to &apos;{throughput1}&apos; on &apos;{entityType1}&apos;, but on &apos;{entityType2}&apos; it was configured to &apos;{throughput2}&apos;. All entity types mapped to the same container &apos;{container}&apos; must be configured with the same provisioned throughput. 的本地化字符串。
        /// </summary>
        internal static string ThroughputMismatch {
            get {
                return ResourceManager.GetString("ThroughputMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provisioned throughput was configured as manual on &apos;{manualEntityType}&apos;, but on &apos;{autoscaleEntityType}&apos; it was configured as autoscale. All entity types mapped to the same container &apos;{container}&apos; must be configured with the same provisioned throughput type. 的本地化字符串。
        /// </summary>
        internal static string ThroughputTypeMismatch {
            get {
                return ResourceManager.GetString("ThroughputTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MongoDB database provider does not support transactions. 的本地化字符串。
        /// </summary>
        internal static string TransactionsNotSupported {
            get {
                return ResourceManager.GetString("TransactionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to bind &apos;{memberType}&apos; &apos;{member}&apos; to an entity projection of &apos;{entityType}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnableToBindMemberToEntityProjection {
            get {
                return ResourceManager.GetString("UnableToBindMemberToEntityProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported operator &apos;{nodeType}&apos; specified for expression of type &apos;{expressionType}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedOperatorForSqlExpression {
            get {
                return ResourceManager.GetString("UnsupportedOperatorForSqlExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conflicts were detected for item with id &apos;{itemId}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UpdateConflict {
            get {
                return ResourceManager.GetString("UpdateConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while saving the the item with id &apos;{itemId}&apos;. See the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string UpdateStoreException {
            get {
                return ResourceManager.GetString("UpdateStoreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;VisitChildren&apos; must be overridden in the class deriving from &apos;SqlExpression&apos;. 的本地化字符串。
        /// </summary>
        internal static string VisitChildrenMustBeOverridden {
            get {
                return ResourceManager.GetString("VisitChildrenMustBeOverridden", resourceCulture);
            }
        }
    }
}
