blank_issues_enabled: true
contact_links:
  - name: Issue with ASP.NET Core
    url:  https://github.com/IoTSharp/IoTSharp.EntityFrameworkCore.MongoDB/issues/issues/new/choose
    about: Please open issues relating to IoTSharp.EntityFrameworkCore.MongoDB.

